# Generated by Django 4.0.4 on 2022-05-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batiment",
            fields=[
                ("id_batiment", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Caracteristique",
            fields=[
                (
                    "id_caracteristique",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("caracteristique", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id_collection", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CollectionObservation",
            fields=[
                (
                    "id_collectionobservation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("ordre", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                ("id_evenement", models.AutoField(primary_key=True, serialize=False)),
                ("id_support", models.IntegerField()),
                ("id_observation", models.IntegerField()),
                ("date", models.DateField()),
                ("numero", models.CharField(blank=True, max_length=255, null=True)),
                ("id_type_evenement", models.IntegerField(blank=True, null=True)),
                ("heure_debut", models.TimeField(blank=True, null=True)),
                ("heure_fin", models.TimeField(blank=True, null=True)),
                ("heure_max_intensite", models.TimeField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "importance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S"),
                            ("1-", "1-"),
                            ("1", "1"),
                            ("1+", "1+"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "brillance",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Faible"), ("N", "Normale"), ("B", "Brillante")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("heure_releve_aire", models.TimeField(blank=True, null=True)),
                ("aire_mesuree", models.FloatField(blank=True, null=True)),
                ("aire_corrigee", models.FloatField(blank=True, null=True)),
                ("remarques", models.TextField(blank=True, null=True)),
                ("interet", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id_image", models.AutoField(primary_key=True, serialize=False)),
                ("fichier", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                ("id_instrument", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LieuObservation",
            fields=[
                (
                    "id_lieu_observation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=255)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("IAU_code", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LieuStockage",
            fields=[
                (
                    "id_lieu_stockage",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("piece", models.CharField(max_length=255)),
                (
                    "emplacement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.batiment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeEvenement",
            fields=[
                (
                    "id_typeevenement",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "abreviation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeObservation",
            fields=[
                (
                    "id_type_observation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=255)),
                ("lg_onde", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Support",
            fields=[
                ("id_support", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FLM", "Film"),
                            ("PLF", "Plan Film"),
                            ("CDR", "CDrom"),
                            ("DVD", "DVD"),
                            ("PLQ", "Plaque"),
                            ("PAP", "Papier"),
                        ],
                        max_length=3,
                    ),
                ),
                ("numero", models.CharField(max_length=255)),
                ("titre", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("diametre_solaire", models.FloatField(blank=True, null=True)),
                ("remarques", models.TextField(blank=True, null=True)),
                ("manquant", models.BooleanField(blank=True, null=True)),
                ("abime", models.BooleanField(blank=True, null=True)),
                ("interet", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.instrument",
                    ),
                ),
                (
                    "lieuobservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.lieuobservation",
                    ),
                ),
                (
                    "lieustockage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.lieustockage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("id_observation", models.AutoField(primary_key=True, serialize=False)),
                ("id_support", models.IntegerField()),
                ("date", models.DateField()),
                ("heure_debut", models.TimeField(blank=True, null=True)),
                ("heure_fin", models.TimeField(blank=True, null=True)),
                ("id_type_observation", models.IntegerField(blank=True, null=True)),
                ("interet", models.BooleanField(blank=True, null=True)),
                ("remarques", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collectionobservation",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.collectionobservation",
                    ),
                ),
                (
                    "support",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.support",
                    ),
                ),
                (
                    "typeobservation",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.typeobservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageSupport",
            fields=[
                (
                    "id_image_support",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.image",
                    ),
                ),
                (
                    "support",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.support",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageObservation",
            fields=[
                (
                    "id_imageobservation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.image",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.observation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageEvenement",
            fields=[
                (
                    "id_imageevenement",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.evenement",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.image",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evenement",
            name="observation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shInvSol.observation"
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="support",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shInvSol.support"
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="typeevenement",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="shInvSol.typeevenement",
            ),
        ),
        migrations.CreateModel(
            name="CaracteristiqueEvenement",
            fields=[
                (
                    "id_caracteristiqueevenement",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "caracteristique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.caracteristique",
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shInvSol.evenement",
                    ),
                ),
            ],
        ),
    ]
