# Generated by Django 4.0.4 on 2022-05-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shInvSol", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evenement",
            old_name="typeevenement",
            new_name="type_evenement",
        ),
        migrations.RemoveField(
            model_name="evenement",
            name="id_observation",
        ),
        migrations.RemoveField(
            model_name="evenement",
            name="id_support",
        ),
        migrations.RemoveField(
            model_name="evenement",
            name="id_type_evenement",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="id_support",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="id_type_observation",
        ),
    ]
