# Generated by Django 4.0.4 on 2022-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shInvSol", "0003_use_timestamp_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="support",
            name="type",
            field=models.CharField(
                choices=[
                    ("FLM", "Film"),
                    ("PLF", "Plan Film"),
                    ("CDR", "CDrom"),
                    ("DVD", "DVD"),
                    ("PLQ", "Plaque"),
                    ("PAP", "Papier"),
                ],
                max_length=255,
            ),
        ),
    ]
