# Generated by Django 4.0.4 on 2022-06-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shInvSol", "0005_collection_observations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="caracteristiques",
            field=models.ManyToManyField(
                related_name="evenements",
                through="shInvSol.CaracteristiqueEvenement",
                to="shInvSol.caracteristique",
            ),
        ),
    ]
