# Generated by Django 4.0.4 on 2022-06-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shInvSol", "0006_evenement_caracteristiques"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observation",
            name="collectionobservation",
        ),
    ]
