# Generated by Django 4.0.4 on 2022-06-03 08:58

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shInvSol", "0007_remove_observation_collectionobservation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imageevenement",
            old_name="id_imageevenement",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="imageobservation",
            old_name="id_imageobservation",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="imagesupport",
            old_name="id_image_support",
            new_name="id",
        ),
        migrations.AddField(
            model_name="imageevenement",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageobservation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imagesupport",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="imageevenement",
            name="image",
            field=filebrowser.fields.FileBrowseField(
                blank=True, max_length=200, verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="imageobservation",
            name="image",
            field=filebrowser.fields.FileBrowseField(
                blank=True, max_length=200, verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="imagesupport",
            name="image",
            field=filebrowser.fields.FileBrowseField(
                blank=True, max_length=200, verbose_name="Image"
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
