# Generated by Django 4.0.4 on 2022-06-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shInvSol', '0008_relations_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='shInvSol.observation'),
        ),
        migrations.AlterField(
            model_name='imagesupport',
            name='support',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='img_s', to='shInvSol.support'),
        ),
        migrations.AlterField(
            model_name='support',
            name='type',
            field=models.CharField(choices=[('Film', 'Film'), ('Plan Film', 'Plan Film'), ('CDrom', 'CDrom'), ('DVD', 'DVD'), ('Plaque', 'Plaque'), ('Papier', 'Papier')], max_length=255),
        ),
    ]
