# Generated by Django 4.0.4 on 2022-06-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='nom_obj',
        ),
        migrations.AddField(
            model_name='observation',
            name='cat_obj',
            field=models.CharField(choices=[('M', 'M'), ('NGC', 'NGC'), ('ARP', 'ARP'), ('-', '-')], default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='observation',
            name='num_obj',
            field=models.TextField(default='Undefined'),
        ),
    ]
