# Generated by Django 4.0.4 on 2022-06-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_observation_nom_obj_observation_cat_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='num_obj',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='temps_exp',
            field=models.IntegerField(),
        ),
    ]
